export const Users=[
    {
        id:1,
        profilePicture : "assets/ProfileImage1.jpg",
        username: "Sofia Dommy",
    },
    {
        id:2,
        profilePicture : "assets/ProfileImage2.jpg",
        username: "James Hidenburg",
    },
    {
        id:3,
        profilePicture : "assets/ProfileImage3.jpg",
        username: "Uwem Wama",
    },
    {
        id:4,
        profilePicture : "assets/ProfileImage4.jpg",
        username: "Max Julian",
    },
    {
        id:5,
        profilePicture : "assets/ProfileImage5.jpg",
        username: "Ruhi Rana",
    },
    {
        id:6,
        profilePicture : "assets/ProfileImage6.jpg",
        username: "Justin Oslo",
    },
    {
        id:7,
        profilePicture : "assets/ProfileImage7.jpg",
        username: "Piky Posly",
    },
    {
        id:8,
        profilePicture : "assets/ProfileImage8.jpg",
        username: "Soha Aesli",
    },
    {
        id:9,
        profilePicture : "assets/ProfileImage9.jpg",
        username: "Dungun Maxos",
    },
    {
        id:10,
        profilePicture : "assets/ProfileImage10.jpg",
        username: "Rustom Rogi",
    },
]
 export const Posts = [
    {
        id:1,
        desc : "Love for all, Hatred for None",
        photo : "assets/Post1.jpg",
        date : "15 sec ago",
        userId : 1,
        Like :223,
        comment : 9,
    },
    {
        id:2,
        desc : "Nature is Every Where",
        photo : "assets/Post2.jpg",
        date : "3 min ago",
        userId : 2,
        Like : 333,
        comment : 5,
    },
    {
        id:3,
        desc : "Traveling is Love",
        photo : "assets/Post3.jpg",
        date : "5 min ago",
        userId : 3,
        Like :695,
        comment : 4,
    },
    {
        id:4,
        desc : "Peace From Below",
        photo : "assets/Post4.jpg",
        date : "10 min ago",
        userId : 4,
        Like :554,
        comment : 96,
    },
    {
        id:5,
        desc : "Roaming in Italy",
        photo : "assets/Post5.jpg",
        date : "12 min ago",
        userId : 5,
        Like :777,
        comment : 91,
    },
    {
        id:6,
        desc : "Animals are more active than us",
        photo : "assets/Post6.jpg",
        date : "15 min ago",
        userId : 6,
        Like :741,
        comment : 29,
    },
    {
        id:7,
        desc : "Gradients",
        photo : "assets/Post7.jpg",
        date : "15 min ago",
        userId : 7,
        Like :123,
        comment : 4,
    },
    {
        id:8,
        desc : "Being a Modal Emphasize Me",
        photo : "assets/Post8.jpg",
        date : "17 min ago",
        userId : 8,
        Like :1203,
        comment : 33,
    },
    {
        id:9,
        desc : "Going Somewhere, No one can go",
        photo : "assets/Post9.jpg",
        date : "35 min ago",
        userId : 9,
        Like :7895,
        comment : 899,
    },
    {
        id:10,
        desc : "Making something new for Me",
        photo : "assets/Post10.jpg",
        date : "45 min ago",
        userId : 10,
        Like :1245,
        comment : 93,
    },
    
 ]